
pipelineName: SampleDeploymentPipeline

source:
  # Source of the code is github
  github:
    # Owner of the repo i.e. for github.com/owner/repo
    owner:          <owner>
    # Repo name i.e. for github.com/owner/repo
    repo:           <repo>
    # Arn of the connection to use to retrieve files from github
    connectionArn:  arn:aws:codeconnections:eu-west-1:<account id>:connection/<connection id>
    # Branch to use when pulling config
    branch:         main
    # Whether to trigger the pipeline when new code is pushed to the repo.
    triggerOnPush:  true
    # Working Directory for the build steps

workDir: ''

destination:
  ecr:
    # Repo Name for the destination.
    repoName: <output repo>
    # If the destination exists or not
    exists: false
    # How to tag the output images:
    # latest - tag with latest
    # commit - tag with full commit hash
    # commit-short - tag with truncated commit hash
    tagRules:
      - latest
      - commit-short
